Version 1.2
UmbrelInfo/UmbrelInfo.github.io pull request #6
Opened 2021-01-02 19:52 UTC by AaronDewes

> Link to SSH instructions in README.md

I have no clue why I wrote this commit description

2021-01-02 19:58 UTC, AaronDewes commented
@Soleone This fixes the issues you pointed out in #3. I also now invited you to become a member of UmbrelInfo.

2021-01-02 20:13 UTC, louneskmt requested changes

2021-01-02 20:13 UTC, louneskmt commented on index.md
> +This page is pat of [Umbrel Plus](https://UmbrelPlus.gitlab.io), a free service extending your Umbrel node.
```suggestion
This page is part of [Umbrel Plus](https://UmbrelPlus.gitlab.io), a free service extending your Umbrel node.
```
Typo

As @Soleone said, you should change the name of your service.

2021-01-02 20:13 UTC, louneskmt commented on troubleshooting.md
> +docker lncli
```suggestion
docker exec lnd lncli
```

2021-01-02 21:13 UTC, Soleone commented on index.md
> +This page is pat of [Umbrel Plus](https://UmbrelPlus.gitlab.io), a free service extending your Umbrel node.
"Umbrel Labs" comes to mind if the goal of the service is to have beta-like features that aren't official part of Umbrel yet, but most of them will be eventually.

2021-01-02 21:14 UTC, Soleone approved these changes

2021-01-03 19:18 UTC, AaronDewes commented
Replaced by #8

2021-01-03 19:18 UTC, closed without merging