Version 1.3
UmbrelInfo/UmbrelInfo.github.io pull request #8
Opened 2021-01-03 19:17 UTC by AaronDewes

Merge needs to wait until UmbrelLabs is actually launched.

2021-01-03 20:05 UTC, louneskmt requested changes
The manual updating command will not work if "updateTo" in update-status.json is empty.

2021-01-04 17:22 UTC, AaronDewes commented
I'll imrpove the docs tomorrow, I forgot about it, then  I'll also launch Umbrel labs.

2021-01-04 21:47 UTC, Soleone approved these changes

2021-01-05 10:36 UTC, AaronDewes commented
I'll merge this commit now, as all requested changes are fixed.

2021-01-05 10:36 UTC, merged